// Seed data: consumed reels + interaction history + candidate technology reels.
// All fictional/anonymized — no real social media data.

import type { Reel, Interaction, EngineConfig } from './types';

// ─── Consumed Reels (the student's actual feed history) ───────────────────

export const SEED_REELS: Reel[] = [
  {
    id: 'r1',
    title: 'When the Java code finally compiles 😤',
    description: 'POV: you fix one bug and create three more. Classic Java developer moment.',
    transcript: 'Java compiler meme — programmer struggles with NullPointerException, generics, and boilerplate. Relatable coding humor.',
    creator: '@codecrafted',
    category: 'Java',
    topics: ['java', 'programming'],
    semanticConcepts: ['java', 'programming', 'software_engineering'],
    educationalValue: 25,
    hypeIndicators: [],
    difficulty: 'Beginner',
    duration: 18,
    thumbnailHue: 280,
  },
  {
    id: 'r2',
    title: 'Day in the life of a software engineer at a startup',
    description: 'Standups, code reviews, debugging, and shipping features. The real dev lifestyle.',
    transcript: 'Software engineer routine — morning standup, pair programming, reviewing pull requests, deploying to production, late-night debugging sessions.',
    creator: '@devlife',
    category: 'Career',
    topics: ['developer_lifestyle', 'career'],
    semanticConcepts: ['developer_lifestyle', 'career', 'software_engineering'],
    educationalValue: 40,
    hypeIndicators: [],
    difficulty: 'Beginner',
    duration: 45,
    thumbnailHue: 300,
  },
  {
    id: 'r3',
    title: 'Coding interview be like... reverse a linked list',
    description: 'The dread of whiteboard interviews. LeetCode grind never ends.',
    transcript: 'Coding interview parody — candidate asked to reverse a linked list on a whiteboard, panic ensues, DSA fundamentals matter.',
    creator: '@interviewbytes',
    category: 'Career',
    topics: ['interview', 'dsa'],
    semanticConcepts: ['interview', 'dsa', 'programming', 'software_engineering'],
    educationalValue: 35,
    hypeIndicators: [],
    difficulty: 'Intermediate',
    duration: 30,
    thumbnailHue: 320,
  },
  {
    id: 'r4',
    title: 'MacBook M3 vs ThinkPad for coding — which wins?',
    description: 'Hardware comparison for developers. Build times, battery, and dev environments.',
    transcript: 'Laptop comparison for programmers — MacBook M3 Pro vs ThinkPad X1 Carbon. Benchmarking compile times, Docker performance, battery life for developers.',
    creator: '@techbench',
    category: 'Hardware',
    topics: ['hardware', 'developer_tools'],
    semanticConcepts: ['hardware', 'developer_tools', 'technology'],
    educationalValue: 50,
    hypeIndicators: [],
    difficulty: 'Beginner',
    duration: 60,
    thumbnailHue: 260,
  },
  {
    id: 'r5',
    title: 'Insane clutch play in Valorant ranked',
    description: '1v5 retake on Ascent. Pure gaming highlight.',
    transcript: 'Valorant ranked gameplay — clutch 1v5 retake, operator flicks, game sense, ranked competitive play.',
    creator: '@clutchking',
    category: 'Gaming',
    topics: ['gaming', 'entertainment'],
    semanticConcepts: ['gaming', 'entertainment'],
    educationalValue: 10,
    hypeIndicators: [],
    difficulty: 'Beginner',
    duration: 25,
    thumbnailHue: 200,
  },
  {
    id: 'r6',
    title: 'Funny cat compilation #shorts',
    description: 'Cats being cats. Pure entertainment.',
    transcript: 'Cat compilation — funny cats knocking things off tables, classic entertainment shorts.',
    creator: '@funnypaws',
    category: 'Entertainment',
    topics: ['entertainment'],
    semanticConcepts: ['entertainment'],
    educationalValue: 5,
    hypeIndicators: [],
    difficulty: 'Beginner',
    duration: 15,
    thumbnailHue: 30,
  },
  {
    id: 'r7',
    title: 'This AI can generate entire apps from a prompt',
    description: 'Demo of an AI coding assistant building a full-stack app in seconds.',
    transcript: 'AI coding assistant demonstration — generating React components, APIs, database schemas from natural language prompts. AI technology showcase.',
    creator: '@aipulse',
    category: 'AI',
    topics: ['ai_tech', 'programming'],
    semanticConcepts: ['ai_tech', 'ai_ml', 'programming', 'software_engineering'],
    educationalValue: 55,
    hypeIndicators: [],
    difficulty: 'Intermediate',
    duration: 50,
    thumbnailHue: 290,
  },
  {
    id: 'r8',
    title: 'Major data breach exposes 50M users',
    description: 'Breaking tech news on a massive cybersecurity incident.',
    transcript: 'Cybersecurity news — major data breach analysis, how the attack happened, what it means for user data, security best practices.',
    creator: '@securewire',
    category: 'News',
    topics: ['cyber_news', 'cybersecurity'],
    semanticConcepts: ['cyber_news', 'cybersecurity', 'technology', 'news'],
    educationalValue: 45,
    hypeIndicators: [],
    difficulty: 'Intermediate',
    duration: 40,
    thumbnailHue: 340,
  },
];

// ─── Interaction history (seeded behavior) ───────────────────────────────

const now = Date.now();
const weekMs = 7 * 24 * 60 * 60 * 1000;

export const SEED_INTERACTIONS: Interaction[] = [
  // Week 1 — entertainment-heavy
  { id: 'i1', reelId: 'r5', type: 'full_watch', watchCompletion: 1, timestamp: now - weekMs * 3 + 1000, week: 1 },
  { id: 'i2', reelId: 'r6', type: 'normal_watch', watchCompletion: 0.7, timestamp: now - weekMs * 3 + 2000, week: 1 },
  // Week 2 — tech interest emerging
  { id: 'i3', reelId: 'r1', type: 'replay', watchCompletion: 1, timestamp: now - weekMs * 2 + 1000, week: 2 },
  { id: 'i4', reelId: 'r1', type: 'like', watchCompletion: 1, timestamp: now - weekMs * 2 + 2000, week: 2 },
  { id: 'i5', reelId: 'r3', type: 'full_watch', watchCompletion: 1, timestamp: now - weekMs * 2 + 3000, week: 2 },
  { id: 'i6', reelId: 'r4', type: 'normal_watch', watchCompletion: 0.85, timestamp: now - weekMs * 2 + 4000, week: 2 },
  // Week 3 — strong tech engagement
  { id: 'i7', reelId: 'r2', type: 'save', watchCompletion: 1, timestamp: now - weekMs + 1000, week: 3 },
  { id: 'i8', reelId: 'r3', type: 'replay', watchCompletion: 1, timestamp: now - weekMs + 2000, week: 3 },
  { id: 'i9', reelId: 'r7', type: 'full_watch', watchCompletion: 1, timestamp: now - weekMs + 3000, week: 3 },
  { id: 'i10', reelId: 'r8', type: 'normal_watch', watchCompletion: 0.6, timestamp: now - weekMs + 4000, week: 3 },
  // Current — continued tech
  { id: 'i11', reelId: 'r2', type: 'full_watch', watchCompletion: 1, timestamp: now - 5000, week: 4 },
  { id: 'i12', reelId: 'r1', type: 'save', watchCompletion: 1, timestamp: now - 4000, week: 4 },
  { id: 'i13', reelId: 'r4', type: 'like', watchCompletion: 0.9, timestamp: now - 3000, week: 4 },
];

// ─── Candidate technology reels (recommendation pool) ─────────────────────

export const CANDIDATE_REELS: Reel[] = [
  {
    id: 'c1',
    title: 'How Data Structures Actually Power Modern Software',
    description: 'Real-world examples of arrays, hash maps, and trees in production systems.',
    transcript: 'Deep dive into data structures — how hash maps power databases, trees enable indexes, graphs drive recommendation engines. Practical DSA in software engineering.',
    creator: '@bytewise',
    category: 'DSA',
    topics: ['dsa', 'programming'],
    semanticConcepts: ['dsa', 'programming', 'software_engineering', 'backend'],
    educationalValue: 91,
    hypeIndicators: [],
    difficulty: 'Intermediate',
    duration: 55,
    thumbnailHue: 285,
    isCandidate: true,
  },
  {
    id: 'c2',
    title: 'System Design: Scaling to 10 Million Users',
    description: 'Load balancing, caching, sharding, and CDN strategies explained clearly.',
    transcript: 'System design fundamentals — horizontal vs vertical scaling, database sharding, Redis caching, CDN strategies, load balancer patterns for high-traffic systems.',
    creator: '@architect',
    category: 'HLD',
    topics: ['system_design', 'backend'],
    semanticConcepts: ['system_design', 'backend', 'cloud', 'software_engineering'],
    educationalValue: 93,
    hypeIndicators: [],
    difficulty: 'Advanced',
    duration: 70,
    thumbnailHue: 310,
    isCandidate: true,
  },
  {
    id: 'c3',
    title: 'Building a REST API with Java and Spring Boot',
    description: 'Step-by-step backend API development with proper architecture.',
    transcript: 'Java Spring Boot tutorial — building REST APIs, dependency injection, JPA repositories, DTOs, error handling, testing. Production backend development.',
    creator: '@backendcraft',
    category: 'Backend',
    topics: ['java', 'backend', 'api'],
    semanticConcepts: ['java', 'backend', 'api', 'programming', 'software_engineering'],
    educationalValue: 88,
    hypeIndicators: [],
    difficulty: 'Intermediate',
    duration: 60,
    thumbnailHue: 295,
    isCandidate: true,
  },
  {
    id: 'c4',
    title: 'Docker and Kubernetes for Developers — The Essentials',
    description: 'Containerize your apps and orchestrate them without the overwhelm.',
    transcript: 'DevOps essentials — Docker containers, Dockerfiles, Kubernetes pods, deployments, services. How container orchestration works in modern software engineering.',
    creator: '@devopsdaily',
    category: 'DevOps',
    topics: ['devops', 'cloud'],
    semanticConcepts: ['devops', 'cloud', 'software_engineering', 'technology'],
    educationalValue: 86,
    hypeIndicators: [],
    difficulty: 'Intermediate',
    duration: 65,
    thumbnailHue: 270,
    isCandidate: true,
  },
  {
    id: 'c5',
    title: 'How Large Language Models Actually Work',
    description: 'Transformers, attention, and training explained without the hype.',
    transcript: 'AI/ML deep dive — transformer architecture, self-attention mechanism, tokenization, training pipelines, how LLMs generate text. Real AI technology explained.',
    creator: '@mldecoded',
    category: 'AI',
    topics: ['ai_tech', 'ai_ml'],
    semanticConcepts: ['ai_tech', 'ai_ml', 'software_engineering', 'programming'],
    educationalValue: 90,
    hypeIndicators: [],
    difficulty: 'Advanced',
    duration: 75,
    thumbnailHue: 330,
    isCandidate: true,
  },
  {
    id: 'c6',
    title: 'AWS for Beginners — Core Services Every Dev Should Know',
    description: 'EC2, S3, Lambda, RDS — the building blocks of cloud computing.',
    transcript: 'AWS fundamentals — EC2 instances, S3 storage, Lambda serverless, RDS databases, IAM. Cloud computing foundations for developers.',
    creator: '@cloudcompass',
    category: 'Cloud',
    topics: ['cloud', 'devops'],
    semanticConcepts: ['cloud', 'technology', 'devops', 'software_engineering'],
    educationalValue: 84,
    hypeIndicators: [],
    difficulty: 'Beginner',
    duration: 50,
    thumbnailHue: 250,
    isCandidate: true,
  },
  {
    id: 'c7',
    title: 'SQL vs NoSQL — How to Choose the Right Database',
    description: 'PostgreSQL, MongoDB, Redis — when to use what and why.',
    transcript: 'Database comparison — relational vs document vs key-value stores. ACID guarantees, scalability tradeoffs, use cases for PostgreSQL, MongoDB, Redis.',
    creator: '@datadecoded',
    category: 'Backend',
    topics: ['database', 'backend'],
    semanticConcepts: ['database', 'backend', 'software_engineering', 'data'],
    educationalValue: 87,
    hypeIndicators: [],
    difficulty: 'Intermediate',
    duration: 55,
    thumbnailHue: 260,
    isCandidate: true,
  },
  {
    id: 'c8',
    title: 'How Hackers Break In — Common Web Vulnerabilities',
    description: 'SQL injection, XSS, CSRF explained with real examples and fixes.',
    transcript: 'Cybersecurity fundamentals — OWASP top 10, SQL injection demos, cross-site scripting, CSRF attacks, input validation, security headers, defensive coding.',
    creator: '@securewire',
    category: 'Cybersecurity',
    topics: ['cyber_news', 'cybersecurity'],
    semanticConcepts: ['cybersecurity', 'cyber_news', 'technology', 'software_engineering'],
    educationalValue: 85,
    hypeIndicators: [],
    difficulty: 'Intermediate',
    duration: 60,
    thumbnailHue: 340,
    isCandidate: true,
  },
  {
    id: 'c9',
    title: 'How GPUs Work — The Hardware Behind AI and Gaming',
    description: 'Parallel processing, CUDA cores, and why GPUs changed everything.',
    transcript: 'GPU hardware explained — parallel processing architecture, CUDA cores, VRAM, ray tracing, how GPUs accelerate AI training and gaming rendering.',
    creator: '@techbench',
    category: 'Hardware',
    topics: ['hardware', 'ai_tech'],
    semanticConcepts: ['hardware', 'developer_tools', 'technology', 'ai_ml'],
    educationalValue: 82,
    hypeIndicators: [],
    difficulty: 'Intermediate',
    duration: 50,
    thumbnailHue: 255,
    isCandidate: true,
  },
  {
    id: 'c10',
    title: 'From Junior to Senior — What Actually Makes You Stand Out',
    description: 'Real career advice for software engineers beyond LeetCode.',
    transcript: 'Career growth — code quality, system thinking, communication, ownership, mentorship. What separates junior from senior software engineers in practice.',
    creator: '@devlife',
    category: 'Career',
    topics: ['developer_lifestyle', 'career'],
    semanticConcepts: ['developer_lifestyle', 'career', 'software_engineering'],
    educationalValue: 80,
    hypeIndicators: [],
    difficulty: 'Beginner',
    duration: 45,
    thumbnailHue: 300,
    isCandidate: true,
  },
  {
    id: 'c11',
    title: '10 AI Tools That Will GUARANTEE You a Job',
    description: 'Clickbait AI tools list with wild promises.',
    transcript: 'Hype AI tools list — guarantees job placement, claims AI will replace all developers, urgency-driven clickbait content with no real substance.',
    creator: '@viraltech',
    category: 'AI',
    topics: ['ai_tech'],
    semanticConcepts: ['ai_tech', 'ai_ml'],
    educationalValue: 15,
    hypeIndicators: ['guarantee', 'clickbait_title', 'urgency', 'job_promise', 'all_caps'],
    difficulty: 'Beginner',
    duration: 20,
    thumbnailHue: 0,
    isCandidate: true,
  },
  {
    id: 'c12',
    title: 'Become an AI Engineer in 7 Days',
    description: 'Wild claim that you can master AI engineering in a week.',
    transcript: 'Clickbait AI course promo — become an AI engineer in 7 days, no experience needed, guaranteed results, urgency and hype-driven marketing.',
    creator: '@viraltech',
    category: 'AI',
    topics: ['ai_tech'],
    semanticConcepts: ['ai_tech', 'ai_ml'],
    educationalValue: 10,
    hypeIndicators: ['guarantee', 'clickbait_title', 'urgency', 'time_pressure', 'no_experience_needed'],
    difficulty: 'Beginner',
    duration: 15,
    thumbnailHue: 10,
    isCandidate: true,
  },
  {
    id: 'c13',
    title: 'This ONE Tool Will Replace All Programmers',
    description: 'Sensationalist claim about a single tool replacing developers.',
    transcript: 'Sensationalist tech content — claims one AI tool will replace all programmers, doom-spelling, no technical depth, pure hype narrative.',
    creator: '@viraltech',
    category: 'AI',
    topics: ['ai_tech'],
    semanticConcepts: ['ai_tech', 'ai_ml'],
    educationalValue: 8,
    hypeIndicators: ['sensationalist', 'replacement_claim', 'clickbait_title', 'doom_narrative', 'all_caps'],
    difficulty: 'Beginner',
    duration: 18,
    thumbnailHue: 350,
    isCandidate: true,
  },
  {
    id: 'c14',
    title: 'Big O Notation Finally Explained Simply',
    description: 'Time and space complexity with intuitive visual examples.',
    transcript: 'DSA fundamentals — Big O notation, time complexity, space complexity, analyzing algorithms, visual examples of O(1), O(n), O(n log n), O(n²).',
    creator: '@bytewise',
    category: 'DSA',
    topics: ['dsa', 'programming'],
    semanticConcepts: ['dsa', 'programming', 'software_engineering'],
    educationalValue: 89,
    hypeIndicators: [],
    difficulty: 'Beginner',
    duration: 40,
    thumbnailHue: 280,
    isCandidate: true,
  },
];

// ─── Default engine configuration ────────────────────────────────────────

export const DEFAULT_CONFIG: EngineConfig = {
  behaviorWeights: {
    skip: -1,
    short_watch: 0.5,
    normal_watch: 1,
    full_watch: 2,
    replay: 3,
    like: 3,
    save: 4,
  },
  scoringWeights: {
    interestMatch: 0.4,
    semanticSimilarity: 0.25,
    educationalValue: 0.2,
    exploration: 0.1,
    hypePenalty: 0.3,
  },
  learningEntertainmentBias: 0.7, // 70% learning by default
};
